// Code generated by hertz generator.

package main

import (
	"log"
	"video/biz/auth"
	"video/biz/cache"
	"video/biz/model"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	cfg := model.LoadConfig()

	db, err := model.InitDB(cfg)
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer model.CloseDB(db)

	if err := cache.InitRedis(cfg); err != nil {
		log.Printf("Warning: Failed to initialize Redis: %v", err)
	}
	defer cache.CloseRedis()

	auth.InitJWT(cfg)

	// 配置文件上传大小限制为 100MB (104857600 bytes)
	// Hertz 默认限制为 4MB，需要增加以支持大文件上传
	maxBodySize := 100 * 1024 * 1024 // 100MB

	h := server.Default(
		server.WithHostPorts(":"+cfg.Server.Port),
		server.WithMaxRequestBodySize(maxBodySize),
	)

	register(h)

	h.Spin()
}
