// Code generated by hertz generator.

package main

import (
	"video/biz/auth"
	handler "video/biz/handler"
	"video/biz/model"
	"video/biz/service"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// 初始化服务
    db := model.DB
    userService := service.NewUserService(db)
    videoService := service.NewVideoService(db)
    interactionService := service.NewInteractionService(db)
    socialService := service.NewSocialService(db)

	// 初始化处理器
    userHandler := handler.NewUserHandler(userService)
    videoHandler := handler.NewVideoHandler(videoService)
    interactionHandler := handler.NewInteractionHandler(interactionService)
    socialHandler := handler.NewSocialHandler(socialService)

	// 认证中间件
    authMiddleware := auth.AuthMiddleware()

	// 健康检查
    r.GET("/ping", handler.Ping)

	// 用户模块
    userGroup := r.Group("/user")
    {
        userGroup.POST("/register", userHandler.Register)
        userGroup.POST("/login", userHandler.Login)
        userGroup.GET("/info", userHandler.GetUserInfo)
        userGroup.PUT("/avatar/upload", authMiddleware, userHandler.UploadAvatar)
    }

	// 视频模块
    videoGroup := r.Group("/video")
    {
        videoGroup.POST("/publish", authMiddleware, videoHandler.PublishVideo)
        videoGroup.GET("/list", videoHandler.GetPublishList)
        videoGroup.POST("/search", videoHandler.SearchVideo)
        videoGroup.GET("/popular", videoHandler.GetPopularVideos)
    }

	// 互动模块
    likeGroup := r.Group("/like")
    {
        likeGroup.POST("/action", authMiddleware, interactionHandler.LikeAction)
        likeGroup.GET("/list", interactionHandler.GetLikeList)
    }

	commentGroup := r.Group("/comment")
    {
        commentGroup.POST("/publish", authMiddleware, interactionHandler.PublishComment)
        commentGroup.GET("/list", interactionHandler.GetCommentList)
        commentGroup.DELETE("/delete", authMiddleware, interactionHandler.DeleteComment)
    }

	// 社交模块
    r.POST("/relation/action", authMiddleware, socialHandler.FollowAction)
    r.GET("/following/list", socialHandler.GetFollowList)
    r.GET("/follower/list", socialHandler.GetFollowerList)
    r.GET("/friends/list", authMiddleware, socialHandler.GetFriendList)
}
